-- 코드를 입력하세요
SELECT
DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') as SALES_DATE,
A.PRODUCT_ID,
A.USER_ID,
A.SALES_AMOUNT
FROM ONLINE_SALE AS A
INNER
JOIN OFFLINE_SALE AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE SUBSTR(A.SALES_DATE,1,7) = '2022-03'
Group by 
A.PRODUCT_ID,
A.USER_ID,
A.SALES_AMOUNT
ORDER BY SALES_DATE, USER_ID DESC;